# Generated by Django 3.1.2 on 2021-08-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('video_file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
