# Generated by Django 2.2.22 on 2021-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
