# Generated by Django 3.2 on 2021-05-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sentiment', '0003_auto_20210517_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataframe', models.JSONField()),
                ('name', models.CharField(max_length=500)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sentiment.document')),
            ],
        ),
    ]
